! Generated by X-Designer Educational version
! This code may not be used in any program
! offered for resale or commercial use.


! Archimed_shell

! Archimed_form_outer

! frame5

! form75

! label70

! rowcol16

! rowcol17

! To_tetra
XApplication*Tetrahedron.alignment: ALIGNMENT_BEGINNING

! To_cube
XApplication*Cube.alignment: ALIGNMENT_BEGINNING

! To_octa
XApplication*Octahedron.alignment: ALIGNMENT_BEGINNING

! To_dode
XApplication*Dodecahedron.alignment: ALIGNMENT_BEGINNING

! To_ico
XApplication*Icosahedron.alignment: ALIGNMENT_BEGINNING

! To_cube4d
XApplication*to_cube4d.alignment: ALIGNMENT_BEGINNING

! To_cubus_simus
XApplication*to_cubus_simus.alignment: ALIGNMENT_BEGINNING

! To_dode_simum
XApplication*to_dode_simum.alignment: ALIGNMENT_BEGINNING

! To_cube_ee
XApplication*to_cube_ee.alignment: ALIGNMENT_BEGINNING

! To_cube_ee_russian
XApplication*to_cube_ee_russian.alignment: ALIGNMENT_BEGINNING

! rowcol18

! To_dual
XApplication*dual.alignment: ALIGNMENT_BEGINNING

! To_trunc
XApplication*truncate.alignment: ALIGNMENT_BEGINNING

! To_truncdode
XApplication*truncate_dode.alignment: ALIGNMENT_BEGINNING

! To_trunccube
XApplication*truncate_cube.alignment: ALIGNMENT_BEGINNING

! To_midpoints_of_edges
XApplication*to_midpoints_of_edges.alignment: ALIGNMENT_BEGINNING

! To_central_point
XApplication*to_central_point.alignment: ALIGNMENT_BEGINNING

! To_central_involution
XApplication*to_central_involution.alignment: ALIGNMENT_BEGINNING

! To_group_on_edges
XApplication*to_group_on_edges.alignment: ALIGNMENT_BEGINNING

! To_relabel_points
XApplication*to_relabel_points.alignment: ALIGNMENT_BEGINNING

! To_ext1
XApplication*to_ext1.alignment: ALIGNMENT_BEGINNING

! To_ext2
XApplication*to_ext2.alignment: ALIGNMENT_BEGINNING

! To_ext3
XApplication*to_ext3.alignment: ALIGNMENT_BEGINNING

! form55

! button14
XApplication*choose.labelString: choose

! button15
XApplication*dismiss.labelString: dismiss


! shell1

! form57

! frame4

! Back_form

! Menu_bar

! File_menu

! menu3

! Quit_mb

! Group_menu

! menu4

! button5

! button12

! button10

! To_asup

! To_ainf

! To_all

! To_poset

! button13

! button1

! button11

! Parameter_menu

! menu5

! Lambda_i_button

! Mendelsohn_button

! Koehler_button

! Km_menu

! menu6

! Compute_km_button

! Show_matrix_button

! Toggle_strong_gens

! Toggle_orderly_generation

! Toggle_TDO

! Toggle_canonical_reps

! Solver_menu

! Lll_b

! Lll_restart_b

! Mckay_b

! Spread_b

! Dance_b

! LS1_b

! LS2_b

! Get_solutions_b

! Check_solutions_b

! Param_b

! Report_menu

! menu10

! Report_b

! Iso_test_canon_b

! Iso_test_sylow_b

! Show_design_b

! Memory_usage_b

! Database_b

! Discreta_title

! Main_form

! Left_form

! Group_form_outer

! frame2

! Group_form

! Label1

! rowcol1

! form6

! label3
XApplication*group:.labelString: group:

! Text_group
XApplication*text.value: 

! form7

! label4
XApplication*v:.labelString: v:

! Text_v
XApplication*text.value: 

! form16

! label11

! Text_order
XApplication*text.value: 

! Param_form_outer

! Disc_param_form

! Label13

! rowcol4

! form11

! label8
XApplication*lambda:.labelString: lambda:

! Text_lambda
XApplication*text.value: 1

! form12

! label9

! Text_p
XApplication*text_p.value: 

! Right_form

! Km_form_outer

! Km_frame

! Disc_km_form

! Label12

! Km_text_rowcol

! form8

! label5
XApplication*t:.labelString: t:

! Text_t
XApplication*text.value: 5

! form9

! label6
XApplication*k:.labelString: k:

! Text_k
XApplication*text.value: 6

! form13

! label10
XApplication*file:.labelString: file:

! Text_file
XApplication*text.value: 

! Km_toggle_rowcol

! rowcol3

! Toggle_k2

! form14

! label2

! Text_k2
XApplication*text_k2.value: 6

! rowcol6

! Toggle_graphical

! Toggle_graph_sn

! form15

! label7

! Text_graphical_n
XApplication*text_graphical_n.value: 6

! Discreta_scrolled_text_

! xdref_9

! xdref_10

! xdref_11


! Database_shell
XApplication*database.title: database

! Database_form_outer

! frame16

! form34

! form35

! label26

! Db_create_b

! Db_add_b

! Db_read_base_b

! Db_read_base2_b

! Db_write_html_b

! Db_dump_b

! Tvt_closure_b

! frame17

! form45

! label27

! rowcol14

! form46

! label38
XApplication*t>=.labelString: t>=

! Db_t_min_text
XApplication*db_t_min_text.value: 

! form47

! label39
XApplication*t<=.labelString: t<=

! Db_t_max_text
XApplication*db_t_max_text.value: 

! form48

! label40
XApplication*v>=.labelString: v>=

! Db_v_min_text
XApplication*db_v_min_text.value: 

! form49

! label41
XApplication*v<=.labelString: v<=

! Db_v_max_text
XApplication*db_v_max_text.value: 

! form50

! label42
XApplication*k>=.labelString: k>=

! Db_k_min_text
XApplication*db_k_min_text.value: 

! form51

! label43
XApplication*k<=.labelString: k<=

! Db_k_max_text
XApplication*db_k_max_text.value: 

! form52

! label44
XApplication*lambda>=.labelString: \\lambda>=

! Db_lambda_min_text
XApplication*db_lambda_min_text.value: 

! form53

! label45
XApplication*lambda<=.labelString: \\lambda<=

! Db_lambda_max_text
XApplication*db_lambda_max_text.value: 

! Db_search_b

! Db_delete_b

! Db_dismiss_b


! Solvable_shell

! Solvable_form_outer

! frame15

! form25

! label35

! rowcol7

! To_solvable_n_m
XApplication*solvable group n#m from catalog.labelString: solvable group n#m from catalog

! rowcol13

! form29

! label36
XApplication*n:.labelString: n:

! Solvable_n_text

! form43

! label37
XApplication*m:.labelString: m:

! Solvable_m_text

! button2
XApplication*choose.labelString: choose

! button3
XApplication*dismiss.labelString: dismiss


! LLL_shell

! LLL_form_outer

! frame11

! form37

! label28

! rowcol11

! form38

! label29
XApplication*c0_factor:.labelString: c0_factor:

! LLL_c0_factor_text
XApplication*text.columns: 10
XApplication*text.value: 20

! form39

! label30
XApplication*beta:.labelString: beta:

! LLL_beta_text
XApplication*text.value: 120

! form40

! label31
XApplication*p:.labelString: p:

! LLL_p_text
XApplication*text.value: 14

! form62

! label49

! Silence_t
XApplication*silence_t.value: 0

! form63

! label50

! Nb_restart_t
XApplication*nb_restart_t.value: 4

! label25

! rowcol5

! form33

! label51

! LS_N_text
XApplication*text.value: 0

! form58

! label52

! LS_max_round_text
XApplication*text.value: 0

! form59

! label53

! LS_max_solutions_text
XApplication*text.value: 0

! form60

! label54

! LS_max_loops_text
XApplication*text.value: 0

! label46

! rowcol15

! form23

! label47

! LLL_graphical_nrow_t
XApplication*text.value: 14

! form54

! label48

! LLL_graphical_ncol_t
XApplication*text.value: 14

! label1

! label14

! rowcol2

! form20

! label15

! Pref_sel_lambda
XApplication*rowcol2*text.value: 1

! form5

! label12

! Pref_sel_first
XApplication*rowcol2*text.value: 1

! form19

! label13

! Pref_sel_len
XApplication*rowcol2*text.value: 1000000

! LLL_ok_b

! LLL_cncl_b


! OTHER_shell

! OTHER_form_outer

! frame10

! form30

! label22

! rowcol10

! To_Sn_short
XApplication*S_n = < (12..n),(12)>.labelString: S_n = < (12..n),(12)>
XApplication*S_n = < (12..n),(12)>.alignment: ALIGNMENT_BEGINNING

! To_Sn_trans
XApplication*S_n = < (12),(23), ..., (n-1,n)>.labelString: S_n = < (12),(23), ..., (n-1,n)>
XApplication*S_n = < (12),(23), ..., (n-1,n)>.alignment: ALIGNMENT_BEGINNING

! To_An
XApplication*A_n.labelString: A_n
XApplication*A_n.alignment: ALIGNMENT_BEGINNING

! To_Dn
XApplication*D_n.labelString: D_n
XApplication*D_n.alignment: ALIGNMENT_BEGINNING

! To_Cn
XApplication*C_n.labelString: C_n
XApplication*C_n.alignment: ALIGNMENT_BEGINNING

! To_HolCn
XApplication*Hol(C_n).labelString: Hol(C_n)
XApplication*Hol(C_n).alignment: ALIGNMENT_BEGINNING

! To_Idn
XApplication*Id_n (trivial group on n points).labelString: Id_n (trivial group on n points)
XApplication*Id_n (trivial group on n points).alignment: ALIGNMENT_BEGINNING

! To_subgroup_of_hol
XApplication*subgroup of holomorph.alignment: ALIGNMENT_BEGINNING

! To_SnwrSm
XApplication*S_n wreath S_m.labelString: S_n \\wreath S_m
XApplication*S_n wreath S_m.alignment: ALIGNMENT_BEGINNING

! rowcol12

! form31

! label23
XApplication*n:.labelString: n:

! OTHER_n_text
XApplication*text.columns: 10

! form32

! label24
XApplication*m:.labelString: m:

! OTHER_m_text
XApplication*text.columns: 10
XApplication*text.value: 

! OTHER_choose_b
XApplication*choose.labelString: choose

! OTHER_dismiss_b
XApplication*dismiss.labelString: dismiss


! LIN_shell

! LIN_form_outer

! frame9

! form26

! label19

! rowcol9

! To_PSL
XApplication*PSL.alignment: ALIGNMENT_BEGINNING

! To_PGL
XApplication*PGL.alignment: ALIGNMENT_BEGINNING

! To_PSSL
XApplication*PSSL.alignment: ALIGNMENT_BEGINNING

! To_PGGL
XApplication*PGGL.alignment: ALIGNMENT_BEGINNING

! To_SL
XApplication*SL.alignment: ALIGNMENT_BEGINNING

! To_GL
XApplication*GL.alignment: ALIGNMENT_BEGINNING

! To_SSL
XApplication*SSL.alignment: ALIGNMENT_BEGINNING

! To_GGL
XApplication*GGL.alignment: ALIGNMENT_BEGINNING

! To_ASL
XApplication*ASL.alignment: ALIGNMENT_BEGINNING

! To_AGL
XApplication*AGL.alignment: ALIGNMENT_BEGINNING

! To_ASSL
XApplication*ASSL.alignment: ALIGNMENT_BEGINNING

! To_AGGL
XApplication*AGGL.alignment: ALIGNMENT_BEGINNING

! To_T
XApplication*to_T.alignment: ALIGNMENT_BEGINNING

! To_PSU_3_q2
XApplication*PSU_3_q2.alignment: ALIGNMENT_BEGINNING

! To_Sz_q
XApplication*Sz_q.alignment: ALIGNMENT_BEGINNING

! form27

! label20
XApplication*q:.labelString: q:

! LIN_q_text
XApplication*text.columns: 10

! form28

! label21
XApplication*n:.labelString: n:

! LIN_n_text
XApplication*text.columns: 10

! LIN_choose_b
XApplication*choose.labelString: choose

! LIN_dismiss_b
XApplication*dismiss.labelString: dismiss


! Sporadic_shell

! Sporadic_form_outer

! frame8

! form24

! label18

! rowcol8

! To_M11
XApplication*M11.labelString: M11
XApplication*M11.alignment: ALIGNMENT_BEGINNING

! To_M12
XApplication*M12.labelString: M12
XApplication*M12.alignment: ALIGNMENT_BEGINNING

! To_M23
XApplication*M23.labelString: M23
XApplication*M23.alignment: ALIGNMENT_BEGINNING

! To_M24
XApplication*M24.labelString: M24
XApplication*M24.alignment: ALIGNMENT_BEGINNING

! To_HS
XApplication*Higman Sims on 176 points.labelString: Higman Sims on 176 points
XApplication*Higman Sims on 176 points.alignment: ALIGNMENT_BEGINNING

! Sporadic_choose_b
XApplication*choose.labelString: choose

! Sporadic_dismiss_b
XApplication*dismiss.labelString: dismiss


! Group_sel_shell

! Gsel_form_outer

! frame6

! form2

! form3

! label16

! form1

! form21

! Gsel_button_form

! Gsel_well_b

! Gsel_linear_b
XApplication*form21*linear.labelString: linear

! Gsel_sporadic_b
XApplication*form21*sporadic.labelString: sporadic

! Gsel_solvable_b

! Gsel_archimed_b

! Gsel_button2_form

! Gsel_file_b

! Gsel_file_text

! Gsel_file_select_b

! Gsel_button3_form

! Gsel_generator_b

! Gsel_generator_text

! label17

! form4

! form10

! form36

! label32

! Gsel_list
XApplication*gesl_list.width: 70

! Gsel_delete_item_b
XApplication*delete item(s).labelString: delete item(s)

! Gsel_clear_all_b
XApplication*clear ALL items !.labelString: clear ALL items !

! form41

! form17

! frame13

! form42

! label33

! Gsel_comma_b
XApplication*,.labelString: ,

! Gsel_dir_sum_b
XApplication*direct sum.labelString: direct sum

! Gsel_dir_prod_b
XApplication*direct product.labelString: direct product

! Gsel_wreath_b
XApplication*wreath product.labelString: wreath product

! Gsel_expo_b
XApplication*exponentiation.labelString: exponentiation

! Gsel_mappings_b
XApplication*on mappings n^m.labelString: on mappings n^m

! form22

! frame14

! form44

! label34

! Gsel_fixpoint_b
XApplication*add a fixpoint.labelString: add a fixpoint

! Gsel_stabilize_b
XApplication*stabilize_point.labelString: stabilize_point

! Gsel_2sets_b
XApplication*induce on 2-sets.labelString: induce on 2-sets

! Gsel_2tuples_b
XApplication*induce on 2-tuples.labelString: induce on 2-tuples

! Gsel_inj2tuples_b
XApplication*induce on injective 2-tuples.labelString: induce on injective 2-tuples

! Gsel_3sets_b
XApplication*induce on 3-sets.labelString: induce on 3-sets

! form56

! I_th_power_b

! Gsel_i_th_text

! form18

! Gsel_choose_b
XApplication*choose.labelString: choose

! Gsel_dismiss_b
XApplication*dismiss.labelString: dismiss

