/*
** Generated by X-Designer Educational version
** This code may not be used in any program
** offered for resale or commercial use.
*/
#ifndef _discreta_h
#define _discreta_h

#define XD_MOTIF

#include <xdclass.h>










extern Widget Archimed_shell;
extern Widget Archimed_form_outer;
extern Widget To_tetra;
extern Widget To_cube;
extern Widget To_octa;
extern Widget To_dode;
extern Widget To_ico;
extern Widget To_cube4d;
extern Widget To_cubus_simus;
extern Widget To_dode_simum;
extern Widget To_cube_ee;
extern Widget To_cube_ee_russian;
extern Widget To_dual;
extern Widget To_trunc;
extern Widget To_truncdode;
extern Widget To_trunccube;
extern Widget To_midpoints_of_edges;
extern Widget To_central_point;
extern Widget To_central_involution;
extern Widget To_group_on_edges;
extern Widget To_relabel_points;
extern Widget To_ext1;
extern Widget To_ext2;
extern Widget To_ext3;

extern Widget shell1;
extern Widget Back_form;
extern Widget Menu_bar;
extern Widget File_menu;
extern Widget Quit_mb;
extern Widget Group_menu;
extern Widget button12;
extern Widget To_asup;
extern Widget To_ainf;
extern Widget To_all;
extern Widget To_poset;
extern Widget Parameter_menu;
extern Widget Lambda_i_button;
extern Widget Mendelsohn_button;
extern Widget Koehler_button;
extern Widget Km_menu;
extern Widget Compute_km_button;
extern Widget Show_matrix_button;
extern Widget Toggle_strong_gens;
extern Widget Toggle_orderly_generation;
extern Widget Toggle_TDO;
extern Widget Toggle_canonical_reps;
extern Widget Solver_menu;
extern Widget Lll_b;
extern Widget Lll_restart_b;
extern Widget Mckay_b;
extern Widget Spread_b;
extern Widget Dance_b;
extern Widget LS1_b;
extern Widget LS2_b;
extern Widget Get_solutions_b;
extern Widget Check_solutions_b;
extern Widget Param_b;
extern Widget Report_menu;
extern Widget Report_b;
extern Widget Iso_test_canon_b;
extern Widget Iso_test_sylow_b;
extern Widget Show_design_b;
extern Widget Memory_usage_b;
extern Widget Database_b;
extern Widget Discreta_title;
extern Widget Main_form;
extern Widget Left_form;
extern Widget Group_form_outer;
extern Widget Group_form;
extern Widget Label1;
extern Widget Text_group;
extern Widget Text_v;
extern Widget Text_order;
extern Widget Param_form_outer;
extern Widget Disc_param_form;
extern Widget Label13;
extern Widget Text_lambda;
extern Widget Text_p;
extern Widget Right_form;
extern Widget Km_form_outer;
extern Widget Km_frame;
extern Widget Disc_km_form;
extern Widget Label12;
extern Widget Km_text_rowcol;
extern Widget Text_t;
extern Widget Text_k;
extern Widget Text_file;
extern Widget Km_toggle_rowcol;
extern Widget Toggle_k2;
extern Widget Text_k2;
extern Widget Toggle_graphical;
extern Widget Toggle_graph_sn;
extern Widget Text_graphical_n;
extern Widget Discreta_scrolled_text_;
extern Widget xdref_9;
extern Widget xdref_10;
extern Widget xdref_11;

extern Widget Database_shell;
extern Widget Database_form_outer;
extern Widget Db_create_b;
extern Widget Db_add_b;
extern Widget Db_read_base_b;
extern Widget Db_read_base2_b;
extern Widget Db_write_html_b;
extern Widget Db_dump_b;
extern Widget Tvt_closure_b;
extern Widget Db_t_min_text;
extern Widget Db_t_max_text;
extern Widget Db_v_min_text;
extern Widget Db_v_max_text;
extern Widget Db_k_min_text;
extern Widget Db_k_max_text;
extern Widget Db_lambda_min_text;
extern Widget Db_lambda_max_text;
extern Widget Db_search_b;
extern Widget Db_delete_b;
extern Widget Db_dismiss_b;

extern Widget Solvable_shell;
extern Widget Solvable_form_outer;
extern Widget To_solvable_n_m;
extern Widget Solvable_n_text;
extern Widget Solvable_m_text;

extern Widget LLL_shell;
extern Widget LLL_form_outer;
extern Widget LLL_c0_factor_text;
extern Widget LLL_beta_text;
extern Widget LLL_p_text;
extern Widget Silence_t;
extern Widget Nb_restart_t;
extern Widget LS_N_text;
extern Widget LS_max_round_text;
extern Widget LS_max_solutions_text;
extern Widget LS_max_loops_text;
extern Widget LLL_graphical_nrow_t;
extern Widget LLL_graphical_ncol_t;
extern Widget Pref_sel_lambda;
extern Widget Pref_sel_first;
extern Widget Pref_sel_len;
extern Widget LLL_ok_b;
extern Widget LLL_cncl_b;

extern Widget OTHER_shell;
extern Widget OTHER_form_outer;
extern Widget To_Sn_short;
extern Widget To_Sn_trans;
extern Widget To_An;
extern Widget To_Dn;
extern Widget To_Cn;
extern Widget To_HolCn;
extern Widget To_Idn;
extern Widget To_subgroup_of_hol;
extern Widget To_SnwrSm;
extern Widget OTHER_n_text;
extern Widget OTHER_m_text;
extern Widget OTHER_choose_b;
extern Widget OTHER_dismiss_b;

extern Widget LIN_shell;
extern Widget LIN_form_outer;
extern Widget To_PSL;
extern Widget To_PGL;
extern Widget To_PSSL;
extern Widget To_PGGL;
extern Widget To_SL;
extern Widget To_GL;
extern Widget To_SSL;
extern Widget To_GGL;
extern Widget To_ASL;
extern Widget To_AGL;
extern Widget To_ASSL;
extern Widget To_AGGL;
extern Widget To_T;
extern Widget To_PSU_3_q2;
extern Widget To_Sz_q;
extern Widget LIN_q_text;
extern Widget LIN_n_text;
extern Widget LIN_choose_b;
extern Widget LIN_dismiss_b;

extern Widget Sporadic_shell;
extern Widget Sporadic_form_outer;
extern Widget To_M11;
extern Widget To_M12;
extern Widget To_M23;
extern Widget To_M24;
extern Widget To_HS;
extern Widget Sporadic_choose_b;
extern Widget Sporadic_dismiss_b;

extern Widget Group_sel_shell;
extern Widget Gsel_form_outer;
extern Widget Gsel_button_form;
extern Widget Gsel_well_b;
extern Widget Gsel_linear_b;
extern Widget Gsel_sporadic_b;
extern Widget Gsel_solvable_b;
extern Widget Gsel_archimed_b;
extern Widget Gsel_button2_form;
extern Widget Gsel_file_b;
extern Widget Gsel_file_text;
extern Widget Gsel_file_select_b;
extern Widget Gsel_button3_form;
extern Widget Gsel_generator_b;
extern Widget Gsel_generator_text;
extern Widget Gsel_list;
extern Widget Gsel_delete_item_b;
extern Widget Gsel_clear_all_b;
extern Widget Gsel_comma_b;
extern Widget Gsel_dir_sum_b;
extern Widget Gsel_dir_prod_b;
extern Widget Gsel_wreath_b;
extern Widget Gsel_expo_b;
extern Widget Gsel_mappings_b;
extern Widget Gsel_fixpoint_b;
extern Widget Gsel_stabilize_b;
extern Widget Gsel_2sets_b;
extern Widget Gsel_2tuples_b;
extern Widget Gsel_inj2tuples_b;
extern Widget Gsel_3sets_b;
extern Widget I_th_power_b;
extern Widget Gsel_i_th_text;
extern Widget Gsel_choose_b;
extern Widget Gsel_dismiss_b;

extern void create_Archimed_shell (Widget parent);

extern void create_shell1 (Display *display, char *app_name, int app_argc, char **app_argv);

extern void create_Database_shell (Widget parent);

extern void create_Solvable_shell (Widget parent);

extern void create_LLL_shell (Widget parent);

extern void create_OTHER_shell (Widget parent);

extern void create_LIN_shell (Widget parent);

extern void create_Sporadic_shell (Widget parent);

extern void create_Group_sel_shell (Widget parent);

#endif
