/*
** Generated by X-Designer Educational version
** This code may not be used in any program
** offered for resale or commercial use.
*/
/*
**LIBS: -lXm -lXt -lX11
*/

#include <stdio.h>
#include <stdlib.h>
#include <X11/Xatom.h>
#include <X11/Intrinsic.h>
#include <X11/Shell.h>

#include <Xm/Xm.h>
#include <X11/StringDefs.h>
#include <Xm/CascadeB.h>
#include <Xm/DialogS.h>
#include <Xm/Form.h>
#include <Xm/Frame.h>
#include <Xm/Label.h>
#include <Xm/List.h>
#include <Xm/PushB.h>
#include <Xm/RowColumn.h>
#include <Xm/ScrollBar.h>
#include <Xm/Separator.h>
#include <Xm/Text.h>
#include <Xm/TextF.h>
#include <Xm/ToggleB.h>
#include <Xm/LabelG.h>


#include <DISCRETA/discreta.h>

#include "discreta.h"
extern void program_init();

extern void cb_linear_toggle(Widget, XtPointer, XtPointer) ;
extern void cb_archimed_choose(Widget, XtPointer, XtPointer) ;
extern void cb_archimed_dismiss(Widget, XtPointer, XtPointer) ;
extern void cb_quit(Widget, XtPointer, XtPointer) ;
extern void cb_choose_aut_group(Widget, XtPointer, XtPointer) ;
extern void cb_create_generators_db(Widget, XtPointer, XtPointer) ;
extern void cb_generators_db_add(Widget, XtPointer, XtPointer) ;
extern void cb_generators_db_dump_id(Widget, XtPointer, XtPointer) ;
extern void cb_generators_db_dump_name(Widget, XtPointer, XtPointer) ;
extern void cb_generators_db_dump_order(Widget, XtPointer, XtPointer) ;
extern void cb_generators_db_dump_degree(Widget, XtPointer, XtPointer) ;
extern void cb_sgl(Widget, XtPointer, XtPointer) ;
extern void cb_show_sgl(Widget, XtPointer, XtPointer) ;
extern void cb_lambda_i(Widget, XtPointer, XtPointer) ;
extern void cb_mendelsohn(Widget, XtPointer, XtPointer) ;
extern void cb_koehler(Widget, XtPointer, XtPointer) ;
extern void cb_compute_KM(Widget, XtPointer, XtPointer) ;
extern void cb_show_KM(Widget, XtPointer, XtPointer) ;
extern void cb_LLL_print_solutions(Widget, XtPointer, XtPointer) ;
extern void cb_LLL(Widget, XtPointer, XtPointer) ;
extern void cb_LLL_parameter(Widget, XtPointer, XtPointer) ;
extern void cb_mckay(Widget, XtPointer, XtPointer) ;
extern void cb_spread(Widget, XtPointer, XtPointer) ;
extern void cb_ls1(Widget, XtPointer, XtPointer) ;
extern void cb_ls2(Widget, XtPointer, XtPointer) ;
extern void cb_get_solutions(Widget, XtPointer, XtPointer) ;
extern void cb_check_solutions(Widget, XtPointer, XtPointer) ;
extern void cb_plesken_asup(Widget, XtPointer, XtPointer) ;
extern void cb_calc_Ik2(Widget, XtPointer, XtPointer) ;
extern void cb_show_Ik2(Widget, XtPointer, XtPointer) ;
extern void cb_calc_Ikk(Widget, XtPointer, XtPointer) ;
extern void cb_show_Ikk(Widget, XtPointer, XtPointer) ;
extern void cb_database(Widget, XtPointer, XtPointer) ;
extern void cb_report(Widget, XtPointer, XtPointer) ;
extern void cb_report_selected(Widget, XtPointer, XtPointer) ;
extern void cb_report_options(Widget, XtPointer, XtPointer) ;
extern void cb_export_GAP(Widget, XtPointer, XtPointer) ;
extern void cb_db_create(Widget, XtPointer, XtPointer) ;
extern void cb_db_add(Widget, XtPointer, XtPointer) ;
extern void cb_db_read_base(Widget, XtPointer, XtPointer) ;
extern void cb_db_read_base_clear_always(Widget, XtPointer, XtPointer) ;
extern void cb_db_write_html(Widget, XtPointer, XtPointer) ;
extern void cb_db_dump(Widget, XtPointer, XtPointer) ;
extern void cb_tvt_closure(Widget, XtPointer, XtPointer) ;
extern void cb_search(Widget, XtPointer, XtPointer) ;
extern void cb_delete(Widget, XtPointer, XtPointer) ;
extern void cb_dismiss(Widget, XtPointer, XtPointer) ;
extern void cb_solvable_toggle(Widget, XtPointer, XtPointer) ;
extern void cb_solvable_choose(Widget, XtPointer, XtPointer) ;
extern void cb_solvable_dismiss(Widget, XtPointer, XtPointer) ;
extern void cb_LLL_ok(Widget, XtPointer, XtPointer) ;
extern void cb_LLL_cncl(Widget, XtPointer, XtPointer) ;
extern void cb_toggle_well_known(Widget, XtPointer, XtPointer) ;
extern void cb_other_choose(Widget, XtPointer, XtPointer) ;
extern void cb_other_dismiss(Widget, XtPointer, XtPointer) ;
extern void cb_linear_choose(Widget, XtPointer, XtPointer) ;
extern void cb_linear_dismiss(Widget, XtPointer, XtPointer) ;
extern void cb_sporadic_toggle(Widget, XtPointer, XtPointer) ;
extern void cb_sporadic_choose(Widget, XtPointer, XtPointer) ;
extern void cb_sporadic_dismiss(Widget, XtPointer, XtPointer) ;
extern void cb_gsel_well_known(Widget, XtPointer, XtPointer) ;
extern void cb_gsel_linear(Widget, XtPointer, XtPointer) ;
extern void cb_gsel_sporadic(Widget, XtPointer, XtPointer) ;
extern void cb_gsel_solvable(Widget, XtPointer, XtPointer) ;
extern void cb_archimed(Widget, XtPointer, XtPointer) ;
extern void cb_gsel_file(Widget, XtPointer, XtPointer) ;
extern void cb_gsel_file_select(Widget, XtPointer, XtPointer) ;
extern void cb_gsel_generator(Widget, XtPointer, XtPointer) ;
extern void cb_gsel_delete_item(Widget, XtPointer, XtPointer) ;
extern void cb_gsel_clear_all(Widget, XtPointer, XtPointer) ;
extern void cb_gsel_comma(Widget, XtPointer, XtPointer) ;
extern void cb_gsel_dir_sum(Widget, XtPointer, XtPointer) ;
extern void cb_gsel_dir_product(Widget, XtPointer, XtPointer) ;
extern void cb_gsel_wreath(Widget, XtPointer, XtPointer) ;
extern void cb_gsel_expo(Widget, XtPointer, XtPointer) ;
extern void cb_gsel_mappings(Widget, XtPointer, XtPointer) ;
extern void cb_gsel_fixpoint(Widget, XtPointer, XtPointer) ;
extern void cb_gsel_stabilize(Widget, XtPointer, XtPointer) ;
extern void cb_gsel_2sets(Widget, XtPointer, XtPointer) ;
extern void cb_gsel_2tuples(Widget, XtPointer, XtPointer) ;
extern void cb_gsel_inj2tuples(Widget, XtPointer, XtPointer) ;
extern void cb_gsel_3sets(Widget, XtPointer, XtPointer) ;
extern void cb_gsel_ith(Widget, XtPointer, XtPointer) ;
extern void cb_gsel_choose(Widget, XtPointer, XtPointer) ;
extern void cb_gsel_dismiss(Widget, XtPointer, XtPointer) ;


XtAppContext app_context;
Display *display;       /*  Display             */

int main (int argc, char **argv)
{
	XtSetLanguageProc ( (XtAppContext) NULL, (XtLanguageProc) NULL, (XtPointer) NULL );
	XtToolkitInitialize ();
	app_context = XtCreateApplicationContext ();
	display = XtOpenDisplay (app_context, NULL, argv[0], "XApplication",
	                         NULL, 0, &argc, argv);
	if (!display)
	{
	    printf("%s: can't open display, exiting...\n", argv[0]);
	    exit (-1);
	}
	discreta_init();
	create_shell1 ( display, argv[0], argc, argv );
	create_Archimed_shell ( shell1 );
	create_Database_shell ( shell1 );
	create_Solvable_shell ( shell1 );
	create_LLL_shell ( shell1 );
	create_OTHER_shell ( shell1 );
	create_LIN_shell ( shell1 );
	create_Sporadic_shell ( shell1 );
	create_Group_sel_shell ( shell1 );
	program_init();
	XtRealizeWidget (shell1);
	XtAppMainLoop (app_context);
	exit (0);
}

