OBJPATH = ../../obj/$(DISCRETA_ARCH)

all: $(OBJPATH)/BIN/discreta_makeKM

$(OBJPATH)/BIN/discreta_makeKM: discreta_makeKM.sh
	cp discreta_makeKM.sh $(OBJPATH)/BIN/discreta_makeKM
	chmod a+x $(OBJPATH)/BIN/discreta_makeKM

clean: ; 

