OBJPATH = ../../obj/$(DISCRETA_ARCH)
OPTIONS=$(LLLOPTIONS)
# OBJ = $(OBJPATH)/MAXCLIQUE

all: $(OBJPATH)/BIN/discreta_solver

$(OBJPATH)/BIN/discreta_solver: discreta_solver.tcl
	cp discreta_solver.tcl $(OBJPATH)/BIN/discreta_solver
	chmod a+x $(OBJPATH)/BIN/discreta_solver

clean: ; 

